name: awesome_side_sheet
description: "|
  A Flutter package for displaying a modal side sheet, following the Material Design 3 specification.
  This package provides a customizable side sheet with a title, body, and optional header and footer actions.
  It offers features such as a back button, close button, and customizable action buttons for easy integration
  into Flutter applications."
version: 0.0.2
homepage: https://github.com/moesaid/awesome_side_sheet

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
